services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_DB: sprintplanner
      POSTGRES_PASSWORD: admin123
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
