version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sprintplanner
    ports:
      - "5432:5432"
    networks:
      - sprintplanner-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - sprintplanner-net
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/docs:/app/docs
    environment:
      - DATABASE_URL=postgres://postgres:admin123@db:5432/sprintplanner?sslmode=disable
      - JIRA_BASE_URL=<jira_base_url>
      - JIRA_API_TOKEN=<personal_access_token>
    networks:
      - sprintplanner-net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - sprintplanner-net
    depends_on:
      - backend

networks:
  sprintplanner-net:
    driver: bridge
